In [5]:
import numpy as np
import pandas as pd
df=pd.read_csv('dataset.csv')
df.shape
df.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country,Infection_Prob
0,98.192545,1,1,0,1,0,1,1,1,1,...,0,1,0,0,0,0.0,0.0,1.0,China,1.0
1,98.140884,1,1,-1,1,0,1,1,1,1,...,0,1,0,0,0,0.0,1.0,0.0,China,0.0
2,101.483542,1,1,0,1,0,1,1,1,1,...,0,1,0,0,0,1.0,0.0,0.0,China,0.0
3,101.280307,1,1,-1,1,0,1,1,1,1,...,0,0,1,0,0,0.0,0.0,1.0,China,0.0
4,100.718450,1,1,0,1,0,1,1,1,1,...,0,0,1,0,0,0.0,1.0,0.0,China,0.0

In [6]:
df.isna().sum()

Fever                      0
Tiredness                  0
Dry-Cough                  0
Difficulty-in-Breathing    0
Sore-Throat                0
None_Sympton               0
Pains                      0
Nasal-Congestion           0
Runny-Nose                 0
Diarrhea                   0
None_Experiencing          0
Age                        0
Age_10-19                  0
Age_20-24                  0
Age_25-59                  0
Age_60+                    0
Gender_Female              0
Gender_Male                0
Gender_Transgender         0
Severity_Mild              0
Severity_Moderate          0
Severity_None              0
Severity_Severe            0
Contact_Dont-Know          1
Contact_No                 1
Contact_Yes                1
Country                    1
Infection_Prob             1
dtype: int64

In [8]:
df=df.drop('Contact_No',axis=1)

In [9]:
df=df.drop('Contact_Dont-Know',axis=1)

In [19]:
df=df.drop('Country',axis=1)

In [46]:
df.replace([np.inf, -np.inf], np.nan).dropna(axis=1)

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Age_25-59,Age_60+,Gender_Female,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Infection_Prob
0,98.192545,1,1,0,1,0,1,1,1,1,...,0,0,0,1,0,1,0,0,0,1.0
1,98.140884,1,1,-1,1,0,1,1,1,1,...,0,0,0,1,0,1,0,0,0,0.0
2,101.483542,1,1,0,1,0,1,1,1,1,...,0,0,0,1,0,1,0,0,0,0.0
3,101.280307,1,1,-1,1,0,1,1,1,1,...,0,0,0,1,0,0,1,0,0,0.0
4,100.718450,1,1,0,1,0,1,1,1,1,...,0,0,0,1,0,0,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66356,100.860534,1,1,-1,0,0,0,0,1,1,...,0,0,1,0,0,0,0,0,1,1.0
66357,100.897065,1,1,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,1,0,0.0
66358,99.250467,1,1,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,1,0,1.0
66359,100.677722,1,1,-1,0,0,0,0,1,1,...,0,0,1,0,0,0,0,1,0,1.0
66360,98.505156,1,1,0,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,0,0.0

In [33]:
# Replacing infinite with nan
df.replace([np.inf, -np.inf], np.nan, inplace=True)
  
# Dropping all the rows with nan values
df.dropna(inplace=True)

In [51]:
np.all(np.isfinite(df))

True

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25, random_state=1)

In [53]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [135]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=1)
np.ravel(y_train)
np.ravel(x_train)
forest.fit(x_train, y_train)

<ipython-input-135-ca0a86bad794>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=1)

In [134]:
model = forest
model.score(x_test,y_test)

0.49634596549385973

In [125]:
import pandas as pd
import math
import numpy as np
from sklearn import preprocessing, model_selection, svm
from sklearn.linear_model import LogisticRegression
import datetime
import pickle

def predictcovid(xin):
    
    #df = pd.read_csv("dataset.csv")
    def data_split(data, ratio):
        np.random.seed(42)
        train, test = model_selection.train_test_split(data, test_size=ratio)
        return train, test

    train_data, test_data = data_split(df, 0.2)

    #Train Test Data
    x_train = train_data[["Fever", "Tiredness", "Dry-Cough", "Difficulty-in-Breathing", "Sore-Throat", "None_Sympton", "Pains", "Nasal-Congestion", "Runny-Nose", "None_Experiencing", "Age"]].to_numpy()
    x_test = test_data[["Fever", "Tiredness", "Dry-Cough", "Difficulty-in-Breathing", "Sore-Throat", "None_Sympton", "Pains", "Nasal-Congestion", "Runny-Nose", "None_Experiencing", "Age"]].to_numpy()

    #print(x_train)
    #Train Test Data

    y_train = train_data[["Infection_Prob"]]
    y_test = test_data[["Infection_Prob"]]

    #print(y_train)
    # Replacing infinite with nan
    df.replace(-1, 1, inplace=True)

    # Dropping all the rows with nan values
    df.dropna(inplace=True)

    df.head()

    np.ravel(y_train)
    np.ravel(y_test)
    
    model = LogisticRegression()
    model.fit(x_train, y_train)

    model = LogisticRegression()
    model.fit(x_train, y_train)
    
    yout=model.predict(xin)
    if(yout==0):
        return "Infected"
    else:
        return "not Infected"

In [127]:
xnew=[[94.33,0,1,0,1,0,1,1,1,0,21]]
np.ravel(xnew)
predictcovid(xnew)

c:\users\joyeeta\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
c:\users\joyeeta\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

'Infected'

In [104]:
xnew=[[94.33,0,1,0,1,0,1,1,1,0,21]]
ynew=clf.predict(xnew)
print(ynew)

[0.]

In [123]:
def probab(xin):
    cnt=0
    if(xnew[0][0]>=99):
        cnt=1
    else:
        cnt=0
    for i in xnew:
        for j in i:
            if(j==1):
                cnt=cnt+1
    return(cnt/7)

In [124]:
xnew=[[94.33,0,1,0,1,0,1,1,1,0,21]]
y=probab(xnew)
print(y)

0.7142857142857143